name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push backend image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/backend:latest -f backend-for-test-app-dist/Dockerfile ./backend-for-test-app-dist
        docker push ghcr.io/${{ github.repository }}/backend:latest

    - name: Build and push frontend image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/frontend:latest -f frontend-for-test-app-dist/Dockerfile ./frontend-for-test-app-dist
        docker push ghcr.io/${{ github.repository }}/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/backend-deployment.yaml
        kubectl apply -f k8s/frontend-deployment.yaml
        kubectl apply -f k8s/persistent-volume-claim.yaml
